// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterScannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterScannerRequest) Reset() {
	*x = RegisterScannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scanner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterScannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterScannerRequest) ProtoMessage() {}

func (x *RegisterScannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterScannerRequest.ProtoReflect.Descriptor instead.
func (*RegisterScannerRequest) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{0}
}

type RegisterScannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveObservables []*Observable `protobuf:"bytes,1,rep,name=active_observables,json=activeObservables,proto3" json:"active_observables,omitempty"`
}

func (x *RegisterScannerResponse) Reset() {
	*x = RegisterScannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scanner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterScannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterScannerResponse) ProtoMessage() {}

func (x *RegisterScannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterScannerResponse.ProtoReflect.Descriptor instead.
func (*RegisterScannerResponse) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterScannerResponse) GetActiveObservables() []*Observable {
	if x != nil {
		return x.ActiveObservables
	}
	return nil
}

type ScannerToObserver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*ScannerToObserver_Register
	//	*ScannerToObserver_ObservedObservable
	//	*ScannerToObserver_RejectObservable
	Msg isScannerToObserver_Msg `protobuf_oneof:"msg"`
}

func (x *ScannerToObserver) Reset() {
	*x = ScannerToObserver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scanner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerToObserver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerToObserver) ProtoMessage() {}

func (x *ScannerToObserver) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerToObserver.ProtoReflect.Descriptor instead.
func (*ScannerToObserver) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{2}
}

func (m *ScannerToObserver) GetMsg() isScannerToObserver_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ScannerToObserver) GetRegister() *RegisterScannerRequest {
	if x, ok := x.GetMsg().(*ScannerToObserver_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ScannerToObserver) GetObservedObservable() string {
	if x, ok := x.GetMsg().(*ScannerToObserver_ObservedObservable); ok {
		return x.ObservedObservable
	}
	return ""
}

func (x *ScannerToObserver) GetRejectObservable() *RejectObservable {
	if x, ok := x.GetMsg().(*ScannerToObserver_RejectObservable); ok {
		return x.RejectObservable
	}
	return nil
}

type isScannerToObserver_Msg interface {
	isScannerToObserver_Msg()
}

type ScannerToObserver_Register struct {
	Register *RegisterScannerRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ScannerToObserver_ObservedObservable struct {
	ObservedObservable string `protobuf:"bytes,2,opt,name=observed_observable,json=observedObservable,proto3,oneof"`
}

type ScannerToObserver_RejectObservable struct {
	RejectObservable *RejectObservable `protobuf:"bytes,3,opt,name=reject_observable,json=rejectObservable,proto3,oneof"`
}

func (*ScannerToObserver_Register) isScannerToObserver_Msg() {}

func (*ScannerToObserver_ObservedObservable) isScannerToObserver_Msg() {}

func (*ScannerToObserver_RejectObservable) isScannerToObserver_Msg() {}

type ObserverToScanner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*ObserverToScanner_Register
	//	*ObserverToScanner_NewObservable
	//	*ObserverToScanner_CancelObservable
	Msg isObserverToScanner_Msg `protobuf_oneof:"msg"`
}

func (x *ObserverToScanner) Reset() {
	*x = ObserverToScanner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scanner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObserverToScanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverToScanner) ProtoMessage() {}

func (x *ObserverToScanner) ProtoReflect() protoreflect.Message {
	mi := &file_scanner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverToScanner.ProtoReflect.Descriptor instead.
func (*ObserverToScanner) Descriptor() ([]byte, []int) {
	return file_scanner_proto_rawDescGZIP(), []int{3}
}

func (m *ObserverToScanner) GetMsg() isObserverToScanner_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ObserverToScanner) GetRegister() *RegisterScannerResponse {
	if x, ok := x.GetMsg().(*ObserverToScanner_Register); ok {
		return x.Register
	}
	return nil
}

func (x *ObserverToScanner) GetNewObservable() *Observable {
	if x, ok := x.GetMsg().(*ObserverToScanner_NewObservable); ok {
		return x.NewObservable
	}
	return nil
}

func (x *ObserverToScanner) GetCancelObservable() string {
	if x, ok := x.GetMsg().(*ObserverToScanner_CancelObservable); ok {
		return x.CancelObservable
	}
	return ""
}

type isObserverToScanner_Msg interface {
	isObserverToScanner_Msg()
}

type ObserverToScanner_Register struct {
	Register *RegisterScannerResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ObserverToScanner_NewObservable struct {
	NewObservable *Observable `protobuf:"bytes,2,opt,name=new_observable,json=newObservable,proto3,oneof"`
}

type ObserverToScanner_CancelObservable struct {
	CancelObservable string `protobuf:"bytes,3,opt,name=cancel_observable,json=cancelObservable,proto3,oneof"`
}

func (*ObserverToScanner_Register) isObserverToScanner_Msg() {}

func (*ObserverToScanner_NewObservable) isObserverToScanner_Msg() {}

func (*ObserverToScanner_CancelObservable) isObserverToScanner_Msg() {}

var File_scanner_proto protoreflect.FileDescriptor

var file_scanner_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e,
	0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x1a, 0x14, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a,
	0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x51, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x62, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e,
	0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0xf4, 0x01, 0x0a, 0x11, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x54, 0x6f, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c,
	0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x13, 0x6f, 0x62, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x12, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x57, 0x0a, 0x11,
	0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e,
	0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74,
	0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xe5, 0x01, 0x0a,
	0x11, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x63, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x4d, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a,
	0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x4b, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61,
	0x69, 0x74, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x0d, 0x6e, 0x65, 0x77, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d,
	0x0a, 0x11, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x10, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x32, 0x7c, 0x0a, 0x0f, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f,
	0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e,
	0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68,
	0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x53, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x54, 0x68, 0x69, 0x73, 0x2d, 0x6f, 0x72, 0x67, 0x2f,
	0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scanner_proto_rawDescOnce sync.Once
	file_scanner_proto_rawDescData = file_scanner_proto_rawDesc
)

func file_scanner_proto_rawDescGZIP() []byte {
	file_scanner_proto_rawDescOnce.Do(func() {
		file_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(file_scanner_proto_rawDescData)
	})
	return file_scanner_proto_rawDescData
}

var file_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scanner_proto_goTypes = []interface{}{
	(*RegisterScannerRequest)(nil),  // 0: com.snoozethis.logwait.RegisterScannerRequest
	(*RegisterScannerResponse)(nil), // 1: com.snoozethis.logwait.RegisterScannerResponse
	(*ScannerToObserver)(nil),       // 2: com.snoozethis.logwait.ScannerToObserver
	(*ObserverToScanner)(nil),       // 3: com.snoozethis.logwait.ObserverToScanner
	(*Observable)(nil),              // 4: com.snoozethis.logwait.Observable
	(*RejectObservable)(nil),        // 5: com.snoozethis.logwait.RejectObservable
}
var file_scanner_proto_depIdxs = []int32{
	4, // 0: com.snoozethis.logwait.RegisterScannerResponse.active_observables:type_name -> com.snoozethis.logwait.Observable
	0, // 1: com.snoozethis.logwait.ScannerToObserver.register:type_name -> com.snoozethis.logwait.RegisterScannerRequest
	5, // 2: com.snoozethis.logwait.ScannerToObserver.reject_observable:type_name -> com.snoozethis.logwait.RejectObservable
	1, // 3: com.snoozethis.logwait.ObserverToScanner.register:type_name -> com.snoozethis.logwait.RegisterScannerResponse
	4, // 4: com.snoozethis.logwait.ObserverToScanner.new_observable:type_name -> com.snoozethis.logwait.Observable
	2, // 5: com.snoozethis.logwait.ObserverService.Communicate:input_type -> com.snoozethis.logwait.ScannerToObserver
	3, // 6: com.snoozethis.logwait.ObserverService.Communicate:output_type -> com.snoozethis.logwait.ObserverToScanner
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scanner_proto_init() }
func file_scanner_proto_init() {
	if File_scanner_proto != nil {
		return
	}
	file_logwait_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_scanner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterScannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scanner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterScannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scanner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerToObserver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scanner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObserverToScanner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_scanner_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ScannerToObserver_Register)(nil),
		(*ScannerToObserver_ObservedObservable)(nil),
		(*ScannerToObserver_RejectObservable)(nil),
	}
	file_scanner_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ObserverToScanner_Register)(nil),
		(*ObserverToScanner_NewObservable)(nil),
		(*ObserverToScanner_CancelObservable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scanner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scanner_proto_goTypes,
		DependencyIndexes: file_scanner_proto_depIdxs,
		MessageInfos:      file_scanner_proto_msgTypes,
	}.Build()
	File_scanner_proto = out.File
	file_scanner_proto_rawDesc = nil
	file_scanner_proto_goTypes = nil
	file_scanner_proto_depIdxs = nil
}
