// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: snoozethis.proto

package logwait

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field  string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Regexp string `protobuf:"bytes,2,opt,name=regexp,proto3" json:"regexp,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetRegexp() string {
	if x != nil {
		return x.Regexp
	}
	return ""
}

type Observable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature string    `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Filters   []*Filter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *Observable) Reset() {
	*x = Observable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Observable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observable) ProtoMessage() {}

func (x *Observable) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observable.ProtoReflect.Descriptor instead.
func (*Observable) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{1}
}

func (x *Observable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Observable) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Observable) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url              string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	LogInstanceToken string `protobuf:"bytes,2,opt,name=log_instance_token,json=logInstanceToken,proto3" json:"log_instance_token,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterRequest) GetLogInstanceToken() string {
	if x != nil {
		return x.LogInstanceToken
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveObservables []*Observable `protobuf:"bytes,1,rep,name=active_observables,json=activeObservables,proto3" json:"active_observables,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetActiveObservables() []*Observable {
	if x != nil {
		return x.ActiveObservables
	}
	return nil
}

type BlahRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*BlahRequest_Register
	//	*BlahRequest_ObservedObservable
	Msg isBlahRequest_Msg `protobuf_oneof:"msg"`
}

func (x *BlahRequest) Reset() {
	*x = BlahRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlahRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlahRequest) ProtoMessage() {}

func (x *BlahRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlahRequest.ProtoReflect.Descriptor instead.
func (*BlahRequest) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{4}
}

func (m *BlahRequest) GetMsg() isBlahRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *BlahRequest) GetRegister() *RegisterRequest {
	if x, ok := x.GetMsg().(*BlahRequest_Register); ok {
		return x.Register
	}
	return nil
}

func (x *BlahRequest) GetObservedObservable() int64 {
	if x, ok := x.GetMsg().(*BlahRequest_ObservedObservable); ok {
		return x.ObservedObservable
	}
	return 0
}

type isBlahRequest_Msg interface {
	isBlahRequest_Msg()
}

type BlahRequest_Register struct {
	Register *RegisterRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type BlahRequest_ObservedObservable struct {
	ObservedObservable int64 `protobuf:"varint,2,opt,name=observed_observable,json=observedObservable,proto3,oneof"`
}

func (*BlahRequest_Register) isBlahRequest_Msg() {}

func (*BlahRequest_ObservedObservable) isBlahRequest_Msg() {}

type BlahResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*BlahResponse_Register
	//	*BlahResponse_NewObservable
	//	*BlahResponse_CancelObservable
	Msg isBlahResponse_Msg `protobuf_oneof:"msg"`
}

func (x *BlahResponse) Reset() {
	*x = BlahResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snoozethis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlahResponse) ProtoMessage() {}

func (x *BlahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snoozethis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlahResponse.ProtoReflect.Descriptor instead.
func (*BlahResponse) Descriptor() ([]byte, []int) {
	return file_snoozethis_proto_rawDescGZIP(), []int{5}
}

func (m *BlahResponse) GetMsg() isBlahResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *BlahResponse) GetRegister() *RegisterResponse {
	if x, ok := x.GetMsg().(*BlahResponse_Register); ok {
		return x.Register
	}
	return nil
}

func (x *BlahResponse) GetNewObservable() *Observable {
	if x, ok := x.GetMsg().(*BlahResponse_NewObservable); ok {
		return x.NewObservable
	}
	return nil
}

func (x *BlahResponse) GetCancelObservable() int64 {
	if x, ok := x.GetMsg().(*BlahResponse_CancelObservable); ok {
		return x.CancelObservable
	}
	return 0
}

type isBlahResponse_Msg interface {
	isBlahResponse_Msg()
}

type BlahResponse_Register struct {
	Register *RegisterResponse `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type BlahResponse_NewObservable struct {
	NewObservable *Observable `protobuf:"bytes,2,opt,name=new_observable,json=newObservable,proto3,oneof"`
}

type BlahResponse_CancelObservable struct {
	CancelObservable int64 `protobuf:"varint,3,opt,name=cancel_observable,json=cancelObservable,proto3,oneof"`
}

func (*BlahResponse_Register) isBlahResponse_Msg() {}

func (*BlahResponse_NewObservable) isBlahResponse_Msg() {}

func (*BlahResponse_CancelObservable) isBlahResponse_Msg() {}

var File_snoozethis_proto protoreflect.FileDescriptor

var file_snoozethis_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68,
	0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x22, 0x36, 0x0a, 0x06, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x67, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x65,
	0x78, 0x70, 0x22, 0x74, 0x0a, 0x0a, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x38,
	0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73,
	0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x22, 0x51, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x2c, 0x0a,
	0x12, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6c, 0x6f, 0x67, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x65, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67,
	0x77, 0x61, 0x69, 0x74, 0x2e, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x45, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a,
	0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x13, 0x6f, 0x62, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x64, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x12, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x05, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0xd9, 0x01, 0x0a, 0x0c, 0x42, 0x6c, 0x61, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f,
	0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x4b, 0x0a, 0x0e,
	0x6e, 0x65, 0x77, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a,
	0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x4f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x4f,
	0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x11, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x5f, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x10, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x32,
	0x69, 0x0a, 0x0e, 0x53, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x54, 0x68, 0x69, 0x73, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x57, 0x0a, 0x04, 0x42, 0x6c, 0x61, 0x68, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x77, 0x61,
	0x69, 0x74, 0x2e, 0x42, 0x6c, 0x61, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x74, 0x68, 0x69, 0x73, 0x2e,
	0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x2e, 0x42, 0x6c, 0x61, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6e, 0x6f, 0x6f, 0x7a, 0x65, 0x54,
	0x68, 0x69, 0x73, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x77, 0x61, 0x69, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_snoozethis_proto_rawDescOnce sync.Once
	file_snoozethis_proto_rawDescData = file_snoozethis_proto_rawDesc
)

func file_snoozethis_proto_rawDescGZIP() []byte {
	file_snoozethis_proto_rawDescOnce.Do(func() {
		file_snoozethis_proto_rawDescData = protoimpl.X.CompressGZIP(file_snoozethis_proto_rawDescData)
	})
	return file_snoozethis_proto_rawDescData
}

var file_snoozethis_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snoozethis_proto_goTypes = []interface{}{
	(*Filter)(nil),           // 0: com.snoozethis.logwait.Filter
	(*Observable)(nil),       // 1: com.snoozethis.logwait.Observable
	(*RegisterRequest)(nil),  // 2: com.snoozethis.logwait.RegisterRequest
	(*RegisterResponse)(nil), // 3: com.snoozethis.logwait.RegisterResponse
	(*BlahRequest)(nil),      // 4: com.snoozethis.logwait.BlahRequest
	(*BlahResponse)(nil),     // 5: com.snoozethis.logwait.BlahResponse
}
var file_snoozethis_proto_depIdxs = []int32{
	0, // 0: com.snoozethis.logwait.Observable.filters:type_name -> com.snoozethis.logwait.Filter
	1, // 1: com.snoozethis.logwait.RegisterResponse.active_observables:type_name -> com.snoozethis.logwait.Observable
	2, // 2: com.snoozethis.logwait.BlahRequest.register:type_name -> com.snoozethis.logwait.RegisterRequest
	3, // 3: com.snoozethis.logwait.BlahResponse.register:type_name -> com.snoozethis.logwait.RegisterResponse
	1, // 4: com.snoozethis.logwait.BlahResponse.new_observable:type_name -> com.snoozethis.logwait.Observable
	4, // 5: com.snoozethis.logwait.SnoozeThisLogs.Blah:input_type -> com.snoozethis.logwait.BlahRequest
	5, // 6: com.snoozethis.logwait.SnoozeThisLogs.Blah:output_type -> com.snoozethis.logwait.BlahResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_snoozethis_proto_init() }
func file_snoozethis_proto_init() {
	if File_snoozethis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snoozethis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snoozethis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Observable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snoozethis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snoozethis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snoozethis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlahRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snoozethis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlahResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_snoozethis_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*BlahRequest_Register)(nil),
		(*BlahRequest_ObservedObservable)(nil),
	}
	file_snoozethis_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*BlahResponse_Register)(nil),
		(*BlahResponse_NewObservable)(nil),
		(*BlahResponse_CancelObservable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snoozethis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snoozethis_proto_goTypes,
		DependencyIndexes: file_snoozethis_proto_depIdxs,
		MessageInfos:      file_snoozethis_proto_msgTypes,
	}.Build()
	File_snoozethis_proto = out.File
	file_snoozethis_proto_rawDesc = nil
	file_snoozethis_proto_goTypes = nil
	file_snoozethis_proto_depIdxs = nil
}
